import { newBlock } from '../../utils';

export const Box = newBlock({
    name: 'box',
    tag: 'div',
    preset: {
        b: 'ek-',
    },
    mods: [
        'background',
        'border',
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'margin-tb',
        'margin-lr',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        'padding-tb',
        'padding-lr',
        'display',
        'position',
        'place',
        'round',
        'round-top',
        'round-right',
        'round-bottom',
        'round-left',
        'round-top-left',
        'round-top-right',
        'round-bottom-left',
        'round-bottom-right',
        'width',
    ],
});
